version: '3.6' 
services:
 frontend:
   image: brunogamacatao/app_frontend
   depends_on: 
    - backend
   ports:
     - "3000:80"
 backend:
   image: brunogamacatao/app_backend
   depends_on: 
    - banco_de_dados
   environment:
     - DATABASE_URL=mongodb://banco_de_dados/app
     - PORTA=5000
   ports:
     - "5000:5000"
 banco_de_dados:
   image: mongo

